### DISCUSSION TITLE
cs_tools tools scriptability export - unexpected keyword argument 'action_object_associations'

### DISCUSSION THREAD

**Discussion by bmofkn** [thoughtspot/cs_tools#83] [Q&A] [answered]
Hi @boonhapus, looks like I posted my question in the wrong place - lol.  Thanks for the response: https://github.com/thoughtspot/cs_tools/discussions/55#discussioncomment-7567446

Just FYI, our CONTEXT_MENU settings have been in place for over six months and no changes were made to the worksheets... but I do see that TS started adding the following code to the worksheet around the beginning of Nov and that's when it started to break (perhaps this was associated with upgrading to v9.6.cl).

```
  action_object_associations:
  - action_name: Open Shipment
    context: CONTEXT_MENU
    enabled: true
```
I'll review your notes in the other comment and attempt to setup a vEnv to get this working.  Thanks a bunch!
